version: '3'
services:
  app:
    build: .
    networks:
      - app
    volumes:
      - .:/app/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - IN_DOCKER=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASS=docker
      - DB_USER=postgres
      - DB_DATABASE=vinli_interview
  db:
    image: vinli/postgres-gis:latest
    networks:
      - app
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - PGPASSWORD=docker
      - PGUSER=postgres  
      - POSTGRES_DB=vinli_interview  

networks:
  app:
    driver: bridge
